### ISSUE TITLE
XV. Simonyi Konferencia szöveg nagyítása

### ISSUE THREAD

**Issue by Freyb** [simonyiszk/konferencia-web#4]
Desktop szélességnél a "XV. Simonyi Konferencia" nagyítása 1.5em-ről 2em-re

**Comment by kripod** [comment]
1366x768 felbontás mellett ez sajnos nem nézne ki jól, túl kevés volna a hely alul (vagy más elrendezés mellett nem volna elég hely a fejléc alatt):

![konf](https://user-images.githubusercontent.com/14854048/34608424-8cd6f0bc-f218-11e7-880d-a5a458a1e657.png)

**Comment by kripod** [comment]
Bár jobban belegondolva ez talán mégiscsak megoldható, és még mobilon is előnyösebb megjelenést eredményezne 😊

**Comment by kripod** [comment]
Végül a javaslatodat követve csak a desktop megjelenésen módosítottam.
