### ISSUE TITLE
Lefelé görgetés

### ISSUE THREAD

**Issue by bence04** [simonyiszk/konferencia-web#6]
Egy link a hero section-be, amitől látszik, hogy le lehet görgetni pl: "tovább olvasás"

**Comment by kissdave** [comment]
Esetleg egy lefelé mutató nyíl, nem design-osabb?

**Comment by kripod** [comment]
Én is inkább a lefelé mutató nyíl felé hajlanék, de manapság szerintem egyre kevesebb oldal alkalmazza ezt. Szerintem fölöslegesen vonná el a felhasználók figyelmét.

**Comment by bence04** [comment]
Valami viszont kéne, mert így semmi nem utal arra, hogy görgethető a tartalom :S

**Comment by kripod** [comment]
Rendben, rajta leszek az ügyön 😉

**Comment by kripod** [comment]
![screenshot](https://user-images.githubusercontent.com/14854048/35170220-b428a79e-fd5f-11e7-843f-8e2861f64242.png)

Kipróbáltam egy nyíl hozzáadását, de szerintem kissé furcsán néz ki ilyen sok nyíl egy oldalon, szóval jobb ötlet híján ezt az issue-t egyelőre lezárom. Szerintem a webet böngészők számára intuitív, hogy egy oldal lefelé görgethető.
